### ISSUE TITLE
Support for iOS 17 interactive widgets

### ISSUE THREAD

**Issue by cbjn** [Chilledheart/yass#648]
Enabling and disabling connection interactions.
[https://developer.apple.com/documentation/widgetkit/adding-interactivity-to-widgets-and-live-activities](url)

**Comment by Chilledheart** [comment]
Thanks for the advice. But it is a bit hard to do now because it is currently written in Objective-C not swift while the new APIs demand Swift. And I need some time to learn some Swift as well. For a short term, there is the way made by [mozillavpn] to add Swift support in CMake project and we can add it if someone can write the UI code.

mozillavpn: https://github.com/mozilla-mobile/mozilla-vpn-client

**Comment by Chilledheart** [comment]
> Thank you for your efforts , here, I have the highest respect.

You're welcome.

**Comment by Chilledheart** [comment]
Close all feature requests to Legacy Platforms for now.
