### ISSUE TITLE
Add openwrt a53 architecture support

### ISSUE THREAD

**Issue by cbjn** [Chilledheart/yass#756]
aarch64_a53

**Comment by Chilledheart** [comment]
[yass-cli_linux-openwrt-release-cortex-a53-1.6.3-47-gbc11413c-1_aarch64_cortex-a53.zip](https://github.com/Chilledheart/yass/files/14290820/yass-cli_linux-openwrt-release-cortex-a53-1.6.3-47-gbc11413c-1_aarch64_cortex-a53.zip)


In progress, can you give this ipk (compressed) a try?

**Comment by Chilledheart** [comment]
You known yass ipk doesn't contain luci support, so you need to start with command line. There is no wiki for the operations because I guess the users of openwrt are familiar with command line. If not, you can start with:
1. download IPK file into your openwrt device (you can do it via curl or scp)
2. install it via `opkg install /path/to/yass-cli.ipk`
3. copy the sample config file to the right location via `cp /etc/yass/config.json.sample /etc/yass/config.json`
4. edit the config file via ` vim /etc/yass/config.json` or you can just scp it into the location ` /etc/yass/config.json`
5. restart the yass_cli service via `/etc/init.d/yass_cli restart`
6. enjoy

If you face other issues in cooperation with openwrt, please feel free to open issues.

I'll close this issue soon because the a53 support is added.

**Comment by Chilledheart** [comment]
And if you are missing with LuCI support, please feel free to open new issue. I guess someone in openwrt community will help you easily.
